name: Mingw-w64 Cross CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: setup mingw
      run: |
        sudo apt update
        sudo apt install gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
    - name: make
      run: |
        mkdir out
        x86_64-w64-mingw32-dlltool -d wslapi.def -l libwslapi.a
        x86_64-w64-mingw32-gcc -std=c99 --pedantic -Wall -Wno-implicit-function-declaration --static main.c -L./ -lshlwapi -lwslapi -o out/Launcher.exe
        find  ./res/* -maxdepth 1 -type d -printf '%f\n' > resl.txt
        xargs -a resl.txt -I{} x86_64-w64-mingw32-windres res/{}/res.rc -o res/{}.o
        xargs -a resl.txt -I{} x86_64-w64-mingw32-gcc -std=c99 --pedantic -Wall -Wno-implicit-function-declaration --static main.c -L./ -lshlwapi -lwslapi res/{}.o -o out/{}.exe      
    - uses: rymndhng/release-on-push-action@master
      name: Release
      id: release
      with:
        bump_version_scheme: minor
    - uses: svenstaro/upload-release-action@v2   
      name: Upload binaries to release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/Launcher.exe
        asset_name: Launcher.exe
        tag: ${{ steps.release.outputs.tag_name }}
        overwrite: true    
